name: Compatibility JSON

on:
  push:
    branches:
      - main

jobs:
  upload-compatibility:
    runs-on: ubuntu-latest
    name: Compatibility JSON
    env:
      JSON_EXT: compat
      JSON_PATH: compatibility.json
      JSON_REMOTE_PATH: test/compatibility.json

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Merge
        uses: ./.github/actions/json-merger

      - name: Upload S3
        uses: mostlytyped/s3-put-action@v1.0.0
        with:
          args: --acl-public
        env:
          LOCAL_FILE: ${{ env.JSON_PATH }}
          REMOTE_FILE: ${{ env.JSON_REMOTE_PATH }}
          AWS_ENDPOINT: s3.us-east-2.amazonaws.com
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
