on: [push]

jobs:
  upload-compatibility:
    runs-on: ubuntu-latest
    name: Compatibility JSON
    description: Creates and uploads compatibility JSON to S3
    env:
      JSON_PATH: /compatibility.json
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Merge
        uses: ./.github/actions/json-merger

      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: ${{ env.JSON_PATH }}
          destination_dir: test/compatibility.json
